import type { DocumentationAnalysis } from "../schemas.js";

export function renderMarkdown(document: DocumentationAnalysis): string {
  const lines = [`# ${document.story.id} — ${document.story.summary || "Technical Documentation"}`, "", "## Story Overview", "", `- Story: ${document.story.id}`, `- Pull request: #${document.pullRequest.number} — ${document.pullRequest.title}`, `- Source branch: ${document.pullRequest.sourceBranch}`, `- Target branch: ${document.pullRequest.targetBranch}`, `- Pull request status: ${document.pullRequest.status}`, "", "## Solution Overview", "", document.solutionOverview || "No solution overview was supplied.", "", "## Implementation by Acceptance Criterion", ""];
  for (const criterion of document.acceptanceCriteria) lines.push(`### ${criterion.id} — ${criterion.criterion}`, "", "#### Implemented Solution", "", criterion.implementation, "", "#### Components Changed", "", bulletList(criterion.components), "", "#### Technical Details", "", bulletList(criterion.technicalDetails), "", "#### Test Source Changes", "", bulletList(criterion.testing), "");
  lines.push("## Salesforce Components Changed", "", bulletList(document.components.map((component) => `${component.path} — ${component.metadataType} (${component.changeType})`)), "", "## Supporting Changes", "", bulletList(document.supportingChanges), "", "## Security and Access Changes", "", bulletList(document.securityChanges), "", "## Dependencies", "", bulletList(document.dependencies), "", "## Testing", "", bulletList([...document.testing.testFiles, ...document.testing.sourceScenarios]), "", `Test execution status: ${document.testing.executionStatus}`, "", "## Deployment Notes", "", bulletList(document.deploymentNotes), "", "## Assumptions", "", bulletList(document.assumptions), "");
  return lines.join("\n");
}

export function renderHtml(document: DocumentationAnalysis): string {
  const criteria = document.acceptanceCriteria.map((criterion) => `<article><h3>${escapeHtml(`${criterion.id} — ${criterion.criterion}`)}</h3><h4>Implemented Solution</h4><p>${htmlText(criterion.implementation)}</p><h4>Components Changed</h4>${htmlList(criterion.components)}<h4>Technical Details</h4>${htmlList(criterion.technicalDetails)}<h4>Test Source Changes</h4>${htmlList(criterion.testing)}</article>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(document.story.id)} — StoryDoc</title><style>body{font-family:system-ui,-apple-system,sans-serif;max-width:960px;margin:40px auto;padding:0 24px;color:#172033;line-height:1.6}h1{color:#0b3d91;border-bottom:2px solid #dbe7ff;padding-bottom:12px}h2{margin-top:36px;color:#0b3d91}h3{margin-top:28px;color:#315b9b}h4{margin-bottom:.25rem}li{margin:.25rem 0}p{white-space:pre-wrap}</style></head><body><h1>${escapeHtml(`${document.story.id} — ${document.story.summary || "Technical Documentation"}`)}</h1><h2>Story Overview</h2><ul><li>Story: ${escapeHtml(document.story.id)}</li><li>Pull request: #${document.pullRequest.number} — ${escapeHtml(document.pullRequest.title)}</li><li>Source branch: ${escapeHtml(document.pullRequest.sourceBranch)}</li><li>Target branch: ${escapeHtml(document.pullRequest.targetBranch)}</li><li>Pull request status: ${escapeHtml(document.pullRequest.status)}</li></ul><h2>Solution Overview</h2><p>${htmlText(document.solutionOverview || "No solution overview was supplied.")}</p><h2>Implementation by Acceptance Criterion</h2>${criteria}<h2>Salesforce Components Changed</h2>${htmlList(document.components.map((component) => `${component.path} — ${component.metadataType} (${component.changeType})`))}<h2>Supporting Changes</h2>${htmlList(document.supportingChanges)}<h2>Security and Access Changes</h2>${htmlList(document.securityChanges)}<h2>Dependencies</h2>${htmlList(document.dependencies)}<h2>Testing</h2>${htmlList([...document.testing.testFiles, ...document.testing.sourceScenarios])}<p><strong>Test execution status:</strong> ${escapeHtml(document.testing.executionStatus)}</p><h2>Deployment Notes</h2>${htmlList(document.deploymentNotes)}<h2>Assumptions</h2>${htmlList(document.assumptions)}</body></html>`;
}

function bulletList(values: string[]): string { return values.length ? values.map((value) => `- ${value}`).join("\n") : "- None identified."; }
function htmlList(values: string[]): string { return `<ul>${(values.length ? values : ["None identified."]).map((value) => `<li>${htmlText(value)}</li>`).join("")}</ul>`; }
function htmlText(value: string): string { return escapeHtml(value).replaceAll("\n", "<br>\n"); }
function escapeHtml(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;"); }
